levels:
  # 1 level
  - green_blocks:
      # Первая линия
      - [5, 29]
      - [85, 29]
      - [165, 29]
      - [245, 29]
      - [325, 29]
      - [405, 29]
      - [485, 29]
      - [565, 29]
      - [645, 29]
      - [725, 29]
      - [805, 29]
      - [885, 29]
      - [965, 29]
      - [1045, 29]
      - [1125, 29]
      # Вторая линия
      - [5, 63]
      - [85, 63]
      - [165, 63]
      - [245, 63]
      - [325, 63]
      - [405, 63]
      - [485, 63]
      - [645, 63]
      - [725, 63]
      - [805, 63]
      - [885, 63]
      - [965, 63]
      - [1045, 63]
      - [1125, 63]
      # Третья линия
      - [5, 97]
      - [85, 97]
      - [165, 97]
      - [245, 97]
      - [325, 97]
      - [405, 97]
      - [725, 97]
      - [805, 97]
      - [885, 97]
      - [965, 97]
      - [1045, 97]
      - [1125, 97]
      # Четверта линия
      - [5, 131]
      - [85, 131]
      - [165, 131]
      - [245, 131]
      - [325, 131]
      - [805, 131]
      - [885, 131]
      - [965, 131]
      - [1045, 131]
      - [1125, 131]
      # Пятая линия
      - [5, 165]
      - [85, 165]
      - [165, 165]
      - [245, 165]
      - [885, 165]
      - [965, 165]
      - [1045, 165]
      - [1125, 165]
      # Шестая линия
      - [5, 199]
      - [85, 199]
      - [165, 199]
      - [965, 199]
      - [1045, 199]
      - [1125, 199]
      # Седьмая линия
      - [5, 233]
      - [85, 233]
      - [1045, 233]
      - [1125, 233]
      # Восьмая линия
      - [5, 267]
      - [1125, 267]
    blue_blocks: []
    red_blocks: []
    rock_blocks: []
    mini_img: "img/level_1.png"
    mini_img_x_pos: 50
    mini_img_y_pos: 100

  # 2 level
  - green_blocks:
      # Левая башня
      - [27, 29]
      - [27, 63]
      - [27, 97]
      - [27, 131]
      - [27, 165]
      - [27, 199]
      - [27, 233]
      - [27, 265]
      - [27, 299]
      - [27, 333]
      - [27, 367]
      - [27, 401]
      - [27, 435]
      - [27, 469]
      - [ 113, 29 ]
      - [ 113, 63 ]
      - [ 113, 97 ]
      - [ 113, 131 ]
      - [ 113, 165 ]
      - [ 113, 199 ]
      - [ 113, 233 ]
      - [ 113, 265 ]
      - [ 113, 299 ]
      - [ 113, 333 ]
      - [ 113, 367 ]
      - [ 113, 401 ]
      - [ 113, 435 ]
      - [ 113, 469 ]
      # Права башня
      - [ 1017, 29 ]
      - [ 1017, 63 ]
      - [ 1017, 97 ]
      - [ 1017, 131 ]
      - [ 1017, 165 ]
      - [ 1017, 199 ]
      - [ 1017, 233 ]
      - [ 1017, 265 ]
      - [ 1017, 299 ]
      - [ 1017, 333 ]
      - [ 1017, 367 ]
      - [ 1017, 401 ]
      - [ 1017, 435 ]
      - [ 1017, 469 ]
      - [ 1103, 29 ]
      - [ 1103, 63 ]
      - [ 1103, 97 ]
      - [ 1103, 131 ]
      - [ 1103, 165 ]
      - [ 1103, 199 ]
      - [ 1103, 233 ]
      - [ 1103, 265 ]
      - [ 1103, 299 ]
      - [ 1103, 333 ]
      - [ 1103, 367 ]
      - [ 1103, 401 ]
      - [ 1103, 435 ]
      - [ 1103, 469 ]
      # Центральный элемент
      - [ 565, 29 ]
      - [ 565, 63 ]
      - [ 565, 97 ]
      - [ 565, 131 ]
      - [ 565, 165 ]
      - [ 565, 199 ]
      - [ 565, 233 ]
      - [ 565, 265 ]
      - [ 565, 299 ]
      - [ 565, 333 ]
      - [ 479, 63 ]
      - [ 479, 97 ]
      - [ 479, 131 ]
      - [ 479, 165 ]
      - [ 479, 199 ]
      - [ 479, 233 ]
      - [ 479, 265 ]
      - [ 479, 299 ]
      - [ 651, 63 ]
      - [ 651, 97 ]
      - [ 651, 131 ]
      - [ 651, 165 ]
      - [ 651, 199 ]
      - [ 651, 233 ]
      - [ 651, 265 ]
      - [ 651, 299 ]
      # Левый крест
      - [ 296, 131 ]
      - [ 210, 165 ]
      - [ 296, 165 ]
      - [ 382, 165 ]
      - [ 296, 199 ]
      # Правый крест
      - [ 834, 131 ]
      - [ 748, 165 ]
      - [ 834, 165 ]
      - [ 920, 165 ]
      - [ 834, 199 ]
    blue_blocks: []
    red_blocks: []
    rock_blocks: []
    mini_img: "img/level_2.png"
    mini_img_x_pos: 270
    mini_img_y_pos: 100

  # 3 level
  - green_blocks:
        # Две ступеньки
        # Первая линия
        - [ 48, 147 ]
        - [ 129, 147 ]
        - [ 210, 147 ]
        - [ 291, 147 ]
        - [ 372, 147 ]
        - [ 750, 147 ]
        - [ 832, 147 ]
        - [ 914, 147 ]
        - [ 996, 147 ]
        - [ 1078, 147 ]
        # Вторая линия
        - [ 48, 185 ]
        - [ 129, 185 ]
        - [ 210, 185 ]
        - [ 291, 185 ]
        - [ 832, 185 ]
        - [ 914, 185 ]
        - [ 996, 185 ]
        - [ 1078, 185 ]
        # Третья линия
        - [ 48, 220 ]
        - [ 129, 220 ]
        - [ 210, 220 ]
        - [ 914, 220 ]
        - [ 996, 220 ]
        - [ 1078, 220 ]
        # Четвертая линия
        - [ 48, 257 ]
        - [ 129, 257 ]
        - [ 996, 257 ]
        - [ 1078, 257 ]
        # Пятая линия
        - [ 48, 292 ]
        - [ 1078, 292 ]
        # Центральный куб
        - [ 477, 198 ]
        - [ 558, 198 ]
        - [ 639, 198 ]
        - [ 477, 232 ]
        - [ 558, 232 ]
        - [ 639, 232 ]
        - [ 477, 266 ]
        - [ 558, 266 ]
        - [ 639, 266 ]
        # Нижняя линия
        - [ 119, 469 ]
        - [ 200, 469 ]
        - [ 281, 469 ]
        - [ 362, 469 ]
        - [ 443, 469 ]
        - [ 524, 469 ]
        - [ 605, 469 ]
        - [ 686, 469 ]
        - [ 767, 469 ]
        - [ 848, 469 ]
        - [ 929, 469 ]
        - [ 1010, 469 ]
    blue_blocks: [ ]
    red_blocks: [ ]
    rock_blocks:
      - [ 466, 147, 254, 13 ]
      - [ 453, 147, 13, 196 ]
      - [ 720, 147, 13, 196 ]
      - [ 466, 330, 68, 13 ]
      - [ 652, 330, 68, 13 ]
    mini_img: "img/level_3.png"
    mini_img_x_pos: 490
    mini_img_y_pos: 100

  # 4 level
  - green_blocks:
      # Левый блок
      - [ 23, 29 ]
      - [ 104, 29 ]
      - [ 185, 29 ]
      - [ 266, 29 ]
      - [ 347, 29 ]
      - [ 23, 64 ]
      - [ 23, 99 ]
      - [ 23, 134 ]
      - [ 347, 64 ]
      - [ 347, 99 ]
      - [ 347, 134 ]
      - [ 23, 169 ]
      - [ 104, 169 ]
      - [ 185, 169 ]
      - [ 266, 169 ]
      - [ 347, 169 ]
      # Правый кубик
      - [ 783, 29 ]
      - [ 864, 29 ]
      - [ 945, 29 ]
      - [ 1026, 29 ]
      - [ 1107, 29 ]
      - [ 783, 64 ]
      - [ 783, 99 ]
      - [ 783, 134 ]
      - [ 1107, 64 ]
      - [ 1107, 99 ]
      - [ 1107, 134 ]
      - [ 783, 169 ]
      - [ 864, 169 ]
      - [ 945, 169 ]
      - [ 1026, 169 ]
      - [ 1107, 169 ]
      # Нижний куб
      - [ 403, 309 ]
      - [ 484, 309 ]
      - [ 565, 309 ]
      - [ 646, 309 ]
      - [ 727, 309 ]
      - [ 403, 344 ]
      - [ 403, 379 ]
      - [ 403, 414 ]
      - [ 727, 344 ]
      - [ 727, 379 ]
      - [ 727, 414 ]
      - [ 403, 449 ]
      - [ 484, 449 ]
      - [ 565, 449 ]
      - [ 646, 449 ]
      - [ 727, 449 ]
    blue_blocks:
      # Левый куб
      - [ 104, 64]
      - [ 185, 64]
      - [ 266, 64]
      - [ 104, 99]
      - [ 185, 99]
      - [ 266, 99]
      - [ 104, 134]
      - [ 185, 134]
      - [ 266, 134]
      # Правый блок
      - [ 864, 64 ]
      - [ 945, 64 ]
      - [ 1026, 64 ]
      - [ 864, 99 ]
      - [ 945, 99 ]
      - [ 1026, 99 ]
      - [ 864, 134 ]
      - [ 945, 134 ]
      - [ 1026, 134 ]
      # Центральный блок
      - [ 484, 344 ]
      - [ 565, 344 ]
      - [ 646, 344 ]
      - [ 484, 379 ]
      - [ 565, 379 ]
      - [ 646, 379 ]
      - [ 484, 414 ]
      - [ 565, 414 ]
      - [ 646, 414 ]
    red_blocks: [  ]
    rock_blocks: [  ]
    mini_img: "img/level_4.png"
    mini_img_x_pos: 710
    mini_img_y_pos: 100

  # 5 level
  - green_blocks:
      # Левая ступенька
      - [ 50, 212 ]
      - [ 131, 212 ]
      - [ 212, 212 ]
      - [ 50, 176 ]
      - [ 131, 176 ]
      - [ 212, 176 ]
      - [ 50, 140 ]
      - [ 131, 140 ]
      - [ 212, 140 ]
      - [ 131, 104 ]
      - [ 212, 104 ]
      - [ 212, 68 ]
      # Правая ступенька
      - [ 1092, 212 ]
      - [ 1011, 212 ]
      - [ 930, 212 ]
      - [ 1092, 176 ]
      - [ 1011, 176 ]
      - [ 930, 176 ]
      - [ 1092, 140 ]
      - [ 1011, 140 ]
      - [ 930, 140 ]
      - [ 1011, 104 ]
      - [ 930, 104 ]
      - [ 930, 68 ]
    blue_blocks:
      # Левый центр столбец
      - [ 512, 68 ]
      - [ 512, 104 ]
      - [ 512, 140 ]
      - [ 512, 176 ]
      - [ 512, 212 ]
      - [ 512, 248 ]
      - [ 512, 284 ]
      # Правый центр столбец
      - [ 617, 68 ]
      - [ 617, 104 ]
      - [ 617, 140 ]
      - [ 617, 176 ]
      - [ 617, 212 ]
      - [ 617, 248 ]
      - [ 617, 284 ]
      # Центральная линия
      - [ 50, 400 ]
      - [ 131, 400 ]
      - [ 212, 400 ]
      - [ 293, 400 ]
      - [ 374, 400 ]
      - [ 465, 400 ]
      - [ 687, 400 ]
      - [ 768, 400 ]
      - [ 849, 400 ]
      - [ 930, 400 ]
      - [ 1011, 400 ]
      - [ 1092, 400 ]
    red_blocks: [ ]
    rock_blocks:
      - [ 293, 65, 13, 196 ]
      - [ 63, 248, 230, 13 ]
      - [ 906, 65, 13, 196 ]
      - [ 919, 248, 230, 13 ]
      - [ 593, 65, 13, 196 ]
    mini_img: "img/level_5.png"
    mini_img_x_pos: 930
    mini_img_y_pos: 100

  # 6 level
  - green_blocks:
      # Левый блок
      - [ 50, 65 ]
      - [ 131, 65 ]
      - [ 212, 65 ]
      - [ 293, 65 ]
      - [ 374, 65 ]
      - [ 50, 102 ]
      - [ 374, 102 ]
      - [ 50, 139 ]
      - [ 374, 139 ]
      - [ 50, 176 ]
      - [ 374, 176 ]
      - [ 50, 213 ]
      - [ 131, 213 ]
      - [ 212, 213 ]
      - [ 293, 213 ]
      - [ 374, 213 ]
      # Правый блок
      - [ 727, 65 ]
      - [ 808, 65 ]
      - [ 889, 65 ]
      - [ 970, 65 ]
      - [ 1051, 65 ]
      - [ 727, 102 ]
      - [ 1051, 102 ]
      - [ 727, 139 ]
      - [ 1051, 139 ]
      - [ 727, 176 ]
      - [ 1051, 176 ]
      - [ 727, 213 ]
      - [ 808, 213 ]
      - [ 889, 213 ]
      - [ 970, 213 ]
      - [ 1051, 213 ]
      # Центр столб
      - [ 565, 65 ]
      - [ 565, 102 ]
      - [ 565, 139 ]
      - [ 565, 176 ]
      - [ 565, 213 ]
      - [ 565, 250 ]
      - [ 565, 287 ]
      - [ 565, 324 ]
      - [ 565, 361 ]
      - [ 565, 398 ]
      - [ 565, 435 ]
    blue_blocks:
      # Левый блок
      - [ 131, 102 ]
      - [ 212, 102 ]
      - [ 293, 102 ]
      - [ 131, 139 ]
      - [ 293, 139 ]
      - [ 131, 176 ]
      - [ 212, 176 ]
      - [ 293, 176 ]
      # Правый блок
      - [ 808, 102 ]
      - [ 889, 102 ]
      - [ 970, 102 ]
      - [ 808, 139 ]
      - [ 970, 139 ]
      - [ 808, 176 ]
      - [ 889, 176 ]
      - [ 970, 176 ]
      # Левая пирамида
      - [ 50, 324 ]
      - [ 131, 324 ]
      - [ 212, 324 ]
      - [ 293, 324 ]
      - [ 374, 324 ]
      - [ 131, 361 ]
      - [ 212, 361 ]
      - [ 293, 361 ]
      - [ 212, 400 ]
      # Правая пирамида
      - [ 727, 324 ]
      - [ 808, 324 ]
      - [ 889, 324 ]
      - [ 970, 324 ]
      - [ 1051, 324 ]
      - [ 808, 361 ]
      - [ 889, 361 ]
      - [ 970, 361 ]
      - [ 889, 400 ]
    red_blocks:
      # Левый блок
      - [ 212, 139 ]
      # Правый блок
      - [ 889, 139 ]
    rock_blocks: []
    mini_img: "img/level_6.png"
    mini_img_x_pos: 50
    mini_img_y_pos: 350

  # 7 level
  - green_blocks:
      # Центр
      - [ 565, 149 ]
      - [ 565, 187 ]
      - [ 565, 225 ]
      - [ 565, 263 ]
      - [ 565, 301 ]
      - [ 482, 187 ]
      - [ 482, 225 ]
      - [ 482, 263 ]
      - [ 648, 187 ]
      - [ 648, 225 ]
      - [ 648, 263 ]
      - [ 399, 225 ]
      - [ 731, 225 ]
    blue_blocks:
      # Центр
      - [ 565, 111 ]
      - [ 482, 149 ]
      - [ 399, 187 ]
      - [ 316, 225 ]
      - [ 399, 263 ]
      - [ 482, 301 ]
      - [ 565, 339 ]
      - [ 648, 301 ]
      - [ 731, 263 ]
      - [ 814, 225 ]
      - [ 731, 187 ]
      - [ 648, 149 ]
      # Левая ступенька
      - [ 46, 301 ]
      - [ 46, 339 ]
      - [ 46, 375 ]
      - [ 129, 339 ]
      - [ 129, 375 ]
      - [ 212, 375 ]
      # Правая ступенька
      - [ 1084, 301 ]
      - [ 1084, 339 ]
      - [ 1084, 375 ]
      - [ 1001, 339 ]
      - [ 1001, 375 ]
      - [ 918, 375 ]
    red_blocks:
      # Центр
      - [ 565, 73 ]
      - [ 482, 111 ]
      - [ 399, 149 ]
      - [ 316, 187 ]
      - [ 233, 225 ]
      - [ 316, 263 ]
      - [ 399, 301 ]
      - [ 482, 339 ]
      - [ 565, 375 ]
      - [ 648, 339 ]
      - [ 731, 301 ]
      - [ 814, 263 ]
      - [ 897, 225 ]
      - [ 814, 187 ]
      - [ 731, 149 ]
      - [ 648, 111 ]
    rock_blocks: []
    mini_img: "img/level_7.png"
    mini_img_x_pos: 270
    mini_img_y_pos: 350

  # 8 level
  - green_blocks:
      # Левый столбец
      - [ 79, 24 ]
      - [ 79, 61 ]
      - [ 79, 98 ]
      - [ 79, 135 ]
      - [ 79, 172 ]
      - [ 79, 209 ]
      - [ 79, 246 ]
      - [ 79, 283 ]
      - [ 79, 320 ]
      - [ 79, 357 ]
      # Правый столбец
      - [ 1051, 24 ]
      - [ 1051, 61 ]
      - [ 1051, 98 ]
      - [ 1051, 135 ]
      - [ 1051, 172 ]
      - [ 1051, 209 ]
      - [ 1051, 246 ]
      - [ 1051, 283 ]
      - [ 1051, 320 ]
      - [ 1051, 357 ]
      # Пирамидка
      - [ 436, 394 ]
      - [ 522, 394 ]
      - [ 608, 394 ]
      - [ 694, 394 ]
      - [ 522, 432 ]
      - [ 608, 432 ]
    blue_blocks:
      # Левый столбец
      - [ 165, 24 ]
      - [ 165, 61 ]
      - [ 165, 98 ]
      - [ 165, 135 ]
      - [ 165, 172 ]
      - [ 165, 209 ]
      - [ 165, 246 ]
      - [ 165, 283 ]
      - [ 165, 320 ]
      - [ 165, 357 ]
      # Правый столбец
      - [ 965, 24 ]
      - [ 965, 61 ]
      - [ 965, 98 ]
      - [ 965, 135 ]
      - [ 965, 172 ]
      - [ 965, 209 ]
      - [ 965, 246 ]
      - [ 965, 283 ]
      - [ 965, 320 ]
      - [ 965, 357 ]
    red_blocks:
      # Левый столбец
      - [ 251, 24 ]
      - [ 251, 61 ]
      - [ 251, 98 ]
      - [ 251, 135 ]
      - [ 251, 172 ]
      - [ 251, 209 ]
      - [ 251, 246 ]
      - [ 251, 283 ]
      - [ 251, 320 ]
      - [ 251, 357 ]
      # Правый столбец
      - [ 879, 24 ]
      - [ 879, 61 ]
      - [ 879, 98 ]
      - [ 879, 135 ]
      - [ 879, 172 ]
      - [ 879, 209 ]
      - [ 879, 246 ]
      - [ 879, 283 ]
      - [ 879, 320 ]
      - [ 879, 357 ]
    rock_blocks:
      - [0, 400, 400, 13]
      - [800, 400, 400, 13]
    mini_img: "img/level_8.png"
    mini_img_x_pos: 490
    mini_img_y_pos: 350

  # 9 level
  - green_blocks:
      # Горизонтальная полоска
      - [ 190, 440 ]
      - [ 275, 440 ]
      - [ 355, 440 ]
      - [ 435, 440 ]
      - [ 515, 440 ]
      - [ 612, 440 ]
      - [ 697, 440 ]
      - [ 777, 440 ]
      - [ 857, 440 ]
      - [ 937, 440 ]
      # Левый столбец
      - [ 457, 109 ]
      - [ 457, 143 ]
      - [ 457, 177 ]
      - [ 457, 211 ]
      - [ 457, 245 ]
      - [ 457, 279 ]
      # Правый столбец
      - [ 673, 109 ]
      - [ 673, 143 ]
      - [ 673, 177 ]
      - [ 673, 211 ]
      - [ 673, 245 ]
      - [ 673, 279 ]
    blue_blocks:
      - [ 355, 474 ]
      - [ 775, 474 ]
      - [ 225, 177 ]
      - [ 936, 177 ]
      - [ 565, 143 ]
      - [ 565, 211 ]
    red_blocks:
      # Левый ромб
      - [ 225, 143 ]
      - [ 145, 177 ]
      - [ 225, 211 ]
      - [ 305, 177 ]
      # Правый ромб
      - [ 936, 143 ]
      - [ 856, 177 ]
      - [ 936, 211 ]
      - [ 1016, 177 ]
      # Центр
      - [ 565, 177 ]
    rock_blocks:
      # Нижняя полоса
      - [ 30, 480, 300, 13 ]
      - [ 450, 480, 300, 13 ]
      - [ 870, 480, 300, 13 ]
      # Левый блок
      - [ 401, 229, 13, 50 ]
      - [ 114, 279, 300, 13 ]
      - [ 114, 100, 13, 179 ]
      - [ 114, 87, 300, 13 ]
      - [ 401, 100, 13, 50 ]
      # Правый блок
      - [ 825, 229, 13, 50 ]
      - [ 825, 279, 300, 13 ]
      - [ 1112, 100, 13, 179 ]
      - [ 825, 87, 300, 13 ]
      - [ 825, 100, 13, 50 ]
    mini_img: "img/level_9.png"
    mini_img_x_pos: 710
    mini_img_y_pos: 350

  # 10 level
  - green_blocks: [ ]
    blue_blocks: [ ]
    red_blocks:
      # Первая линия
      - [ 155, 36 ]
      - [ 237, 36 ]
      - [ 319, 36 ]
      - [ 401, 36 ]
      - [ 483, 36 ]
      - [ 565, 36 ]
      - [ 647, 36 ]
      - [ 729, 36 ]
      - [ 811, 36 ]
      - [ 893, 36 ]
      # Вторая линия
      - [ 155, 75 ]
      - [ 237, 75 ]
      - [ 319, 75 ]
      - [ 401, 75 ]
      - [ 483, 75 ]
      - [ 565, 75 ]
      - [ 647, 75 ]
      - [ 729, 75 ]
      - [ 811, 75 ]
      - [ 893, 75 ]
      # Третья линия
      - [ 155, 114 ]
      - [ 237, 114 ]
      - [ 319, 114 ]
      - [ 401, 114 ]
      - [ 483, 114 ]
      - [ 565, 114 ]
      - [ 647, 114 ]
      - [ 729, 114 ]
      - [ 811, 114 ]
      - [ 893, 114 ]
      # Четвертая линия
      - [ 155, 153 ]
      - [ 237, 153 ]
      - [ 319, 153 ]
      - [ 401, 153 ]
      - [ 483, 153 ]
      - [ 565, 153 ]
      - [ 647, 153 ]
      - [ 729, 153 ]
      - [ 811, 153 ]
      - [ 893, 153 ]
      # Пятая линия
      - [ 155, 192 ]
      - [ 237, 192 ]
      - [ 319, 192 ]
      - [ 401, 192 ]
      - [ 483, 192 ]
      - [ 565, 192 ]
      - [ 647, 192 ]
      - [ 729, 192 ]
      - [ 811, 192 ]
      - [ 893, 192 ]
      # Шестая линия
      - [ 155, 231 ]
      - [ 237, 231 ]
      - [ 319, 231 ]
      - [ 401, 231 ]
      - [ 483, 231 ]
      - [ 565, 231 ]
      - [ 647, 231 ]
      - [ 729, 231 ]
      - [ 811, 231 ]
      - [ 893, 231 ]
      # Седьмая линия
      - [ 155, 270 ]
      - [ 237, 270 ]
      - [ 319, 270 ]
      - [ 401, 270 ]
      - [ 483, 270 ]
      - [ 565, 270 ]
      - [ 647, 270 ]
      - [ 729, 270 ]
      - [ 811, 270 ]
      - [ 893, 270 ]
    rock_blocks: []
    mini_img: "img/level_10.png"
    mini_img_x_pos: 930
    mini_img_y_pos: 350