reference:
  - text: "ARKANOID"
    x_pos: 500
    y_pos: 50
    size: 45
  - text: "Управление:"
    x_pos: 48
    y_pos: 100
    size: 30
  - text: "Управление площадкой с помощью кнопок 'Влево', 'Вправо'."
    x_pos: 48
    y_pos: 135
    size: 20
  - text: "Модификаторы:"
    x_pos: 48
    y_pos: 170
    size: 30
  - text: "- 'Удлиннитель (E)' - увеличивает длину платформы."
    x_pos: 48
    y_pos: 205
    size: 20
  - text: "- 'Укоротитель (R)' - уменьшает длину платформы."
    x_pos: 48
    y_pos: 240
    size: 20
  - text: "- 'Замедлитель (S)' - уменьшает скорость всех шаров."
    x_pos: 48
    y_pos: 275
    size: 20
  - text: "- 'Дубликат (D)' - добавляет новый шар на экран."
    x_pos: 48
    y_pos: 310
    size: 20
  - text: "- 'Блокировщик (B)' - создает платформу, блокирующую падение меча."
    x_pos: 48
    y_pos: 345
    size: 20
  - text: "Победа/Проигрыш:"
    x_pos: 48
    y_pos: 380
    size: 30
  - text: "Если вы собьете все кирпичи, вы выиграете. Если последний ваш шар коснется пола, вы проиграли."
    x_pos: 48
    y_pos: 415
    size: 20
  - text: "Типы кирпичей:"
    x_pos: 48
    y_pos: 450
    size: 30
  - text: "Зеленые - ломаются с одного удара"
    x_pos: 48
    y_pos: 485
    size: 20
  - text: "Синие - ломаются с двух ударов"
    x_pos: 48
    y_pos: 520
    size: 20
  - text: "Красные - ломаются с трех ударов"
    x_pos: 48
    y_pos: 555
    size: 20
  - text: "Каменные - вообще не ломаются"
    x_pos: 48
    y_pos: 590
    size: 20
  - text: "Отбивайте шарик платформой и разбейте все кирпичи! Удачи!"
    x_pos: 150
    y_pos: 670
    size: 30